// <auto-generated/>
using ApiSdk.Jobs.Add;
using ApiSdk.Jobs.All;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Jobs
{
    /// <summary>
    /// Builds and executes requests for operations under \jobs
    /// </summary>
    public class JobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add property</summary>
        public ApiSdk.Jobs.Add.AddRequestBuilder Add
        {
            get => new ApiSdk.Jobs.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The all property</summary>
        public ApiSdk.Jobs.All.AllRequestBuilder All
        {
            get => new ApiSdk.Jobs.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/jobs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/jobs", rawUrl)
        {
        }
    }
}
