// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class Assembly : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The codeBase property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeBase { get; private set; }
#nullable restore
#else
        public string CodeBase { get; private set; }
#endif
        /// <summary>The customAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeData>? CustomAttributes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeData> CustomAttributes { get; private set; }
#endif
        /// <summary>The definedTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.TypeInfo>? DefinedTypes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.TypeInfo> DefinedTypes { get; private set; }
#endif
        /// <summary>The entryPoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.MethodInfo? EntryPoint { get; set; }
#nullable restore
#else
        public ApiSdk.Models.MethodInfo EntryPoint { get; set; }
#endif
        /// <summary>The escapedCodeBase property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EscapedCodeBase { get; private set; }
#nullable restore
#else
        public string EscapedCodeBase { get; private set; }
#endif
        /// <summary>The exportedTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.TypeObject>? ExportedTypes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.TypeObject> ExportedTypes { get; private set; }
#endif
        /// <summary>The fullName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; private set; }
#nullable restore
#else
        public string FullName { get; private set; }
#endif
        /// <summary>The globalAssemblyCache property</summary>
        [Obsolete("")]
        public bool? GlobalAssemblyCache { get; private set; }
        /// <summary>The hostContext property</summary>
        public long? HostContext { get; private set; }
        /// <summary>The imageRuntimeVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageRuntimeVersion { get; private set; }
#nullable restore
#else
        public string ImageRuntimeVersion { get; private set; }
#endif
        /// <summary>The isCollectible property</summary>
        public bool? IsCollectible { get; private set; }
        /// <summary>The isDynamic property</summary>
        public bool? IsDynamic { get; private set; }
        /// <summary>The isFullyTrusted property</summary>
        public bool? IsFullyTrusted { get; private set; }
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; private set; }
#nullable restore
#else
        public string Location { get; private set; }
#endif
        /// <summary>The manifestModule property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.Module? ManifestModule { get; set; }
#nullable restore
#else
        public ApiSdk.Models.Module ManifestModule { get; set; }
#endif
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.Module>? Modules { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.Module> Modules { get; private set; }
#endif
        /// <summary>The reflectionOnly property</summary>
        public bool? ReflectionOnly { get; private set; }
        /// <summary>The securityRuleSet property</summary>
        public int? SecurityRuleSet { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.Assembly"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.Assembly CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.Assembly();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codeBase", n => { CodeBase = n.GetStringValue(); } },
                { "customAttributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeData>(ApiSdk.Models.CustomAttributeData.CreateFromDiscriminatorValue)?.ToList(); } },
                { "definedTypes", n => { DefinedTypes = n.GetCollectionOfObjectValues<ApiSdk.Models.TypeInfo>(ApiSdk.Models.TypeInfo.CreateFromDiscriminatorValue)?.ToList(); } },
                { "entryPoint", n => { EntryPoint = n.GetObjectValue<ApiSdk.Models.MethodInfo>(ApiSdk.Models.MethodInfo.CreateFromDiscriminatorValue); } },
                { "escapedCodeBase", n => { EscapedCodeBase = n.GetStringValue(); } },
                { "exportedTypes", n => { ExportedTypes = n.GetCollectionOfObjectValues<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue)?.ToList(); } },
                { "fullName", n => { FullName = n.GetStringValue(); } },
                { "globalAssemblyCache", n => { GlobalAssemblyCache = n.GetBoolValue(); } },
                { "hostContext", n => { HostContext = n.GetLongValue(); } },
                { "imageRuntimeVersion", n => { ImageRuntimeVersion = n.GetStringValue(); } },
                { "isCollectible", n => { IsCollectible = n.GetBoolValue(); } },
                { "isDynamic", n => { IsDynamic = n.GetBoolValue(); } },
                { "isFullyTrusted", n => { IsFullyTrusted = n.GetBoolValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "manifestModule", n => { ManifestModule = n.GetObjectValue<ApiSdk.Models.Module>(ApiSdk.Models.Module.CreateFromDiscriminatorValue); } },
                { "modules", n => { Modules = n.GetCollectionOfObjectValues<ApiSdk.Models.Module>(ApiSdk.Models.Module.CreateFromDiscriminatorValue)?.ToList(); } },
                { "reflectionOnly", n => { ReflectionOnly = n.GetBoolValue(); } },
                { "securityRuleSet", n => { SecurityRuleSet = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ApiSdk.Models.MethodInfo>("entryPoint", EntryPoint);
            writer.WriteObjectValue<ApiSdk.Models.Module>("manifestModule", ManifestModule);
            writer.WriteIntValue("securityRuleSet", SecurityRuleSet);
        }
    }
}
