// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class ContainerListResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The command property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>The imageID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageID { get; set; }
#nullable restore
#else
        public string ImageID { get; set; }
#endif
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.ContainerListResponse_labels? Labels { get; set; }
#nullable restore
#else
        public ApiSdk.Models.ContainerListResponse_labels Labels { get; set; }
#endif
        /// <summary>The mounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.MountPoint>? Mounts { get; set; }
#nullable restore
#else
        public List<ApiSdk.Models.MountPoint> Mounts { get; set; }
#endif
        /// <summary>The names property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Names { get; set; }
#nullable restore
#else
        public List<string> Names { get; set; }
#endif
        /// <summary>The networkSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.SummaryNetworkSettings? NetworkSettings { get; set; }
#nullable restore
#else
        public ApiSdk.Models.SummaryNetworkSettings NetworkSettings { get; set; }
#endif
        /// <summary>The ports property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.Port>? Ports { get; set; }
#nullable restore
#else
        public List<ApiSdk.Models.Port> Ports { get; set; }
#endif
        /// <summary>The sizeRootFs property</summary>
        public long? SizeRootFs { get; set; }
        /// <summary>The sizeRw property</summary>
        public long? SizeRw { get; set; }
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.ContainerListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.ContainerListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.ContainerListResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "command", n => { Command = n.GetStringValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "imageID", n => { ImageID = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<ApiSdk.Models.ContainerListResponse_labels>(ApiSdk.Models.ContainerListResponse_labels.CreateFromDiscriminatorValue); } },
                { "mounts", n => { Mounts = n.GetCollectionOfObjectValues<ApiSdk.Models.MountPoint>(ApiSdk.Models.MountPoint.CreateFromDiscriminatorValue)?.ToList(); } },
                { "names", n => { Names = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                { "networkSettings", n => { NetworkSettings = n.GetObjectValue<ApiSdk.Models.SummaryNetworkSettings>(ApiSdk.Models.SummaryNetworkSettings.CreateFromDiscriminatorValue); } },
                { "ports", n => { Ports = n.GetCollectionOfObjectValues<ApiSdk.Models.Port>(ApiSdk.Models.Port.CreateFromDiscriminatorValue)?.ToList(); } },
                { "sizeRootFs", n => { SizeRootFs = n.GetLongValue(); } },
                { "sizeRw", n => { SizeRw = n.GetLongValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("command", Command);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("image", Image);
            writer.WriteStringValue("imageID", ImageID);
            writer.WriteObjectValue<ApiSdk.Models.ContainerListResponse_labels>("labels", Labels);
            writer.WriteCollectionOfObjectValues<ApiSdk.Models.MountPoint>("mounts", Mounts);
            writer.WriteCollectionOfPrimitiveValues<string>("names", Names);
            writer.WriteObjectValue<ApiSdk.Models.SummaryNetworkSettings>("networkSettings", NetworkSettings);
            writer.WriteCollectionOfObjectValues<ApiSdk.Models.Port>("ports", Ports);
            writer.WriteLongValue("sizeRootFs", SizeRootFs);
            writer.WriteLongValue("sizeRw", SizeRw);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("status", Status);
        }
    }
}
