// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class CustomAttributeData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The attributeType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? AttributeType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject AttributeType { get; set; }
#endif
        /// <summary>The constructor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.ConstructorInfo? Constructor { get; set; }
#nullable restore
#else
        public ApiSdk.Models.ConstructorInfo Constructor { get; set; }
#endif
        /// <summary>The constructorArguments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeTypedArgument>? ConstructorArguments { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeTypedArgument> ConstructorArguments { get; private set; }
#endif
        /// <summary>The namedArguments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeNamedArgument>? NamedArguments { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeNamedArgument> NamedArguments { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.CustomAttributeData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.CustomAttributeData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.CustomAttributeData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributeType", n => { AttributeType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
                { "constructor", n => { Constructor = n.GetObjectValue<ApiSdk.Models.ConstructorInfo>(ApiSdk.Models.ConstructorInfo.CreateFromDiscriminatorValue); } },
                { "constructorArguments", n => { ConstructorArguments = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeTypedArgument>(ApiSdk.Models.CustomAttributeTypedArgument.CreateFromDiscriminatorValue)?.ToList(); } },
                { "namedArguments", n => { NamedArguments = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeNamedArgument>(ApiSdk.Models.CustomAttributeNamedArgument.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("attributeType", AttributeType);
            writer.WriteObjectValue<ApiSdk.Models.ConstructorInfo>("constructor", Constructor);
        }
    }
}
