// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class CustomAttributeNamedArgument : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The isField property</summary>
        public bool? IsField { get; private set; }
        /// <summary>The memberInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.MemberInfo? MemberInfo { get; set; }
#nullable restore
#else
        public ApiSdk.Models.MemberInfo MemberInfo { get; set; }
#endif
        /// <summary>The memberName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberName { get; private set; }
#nullable restore
#else
        public string MemberName { get; private set; }
#endif
        /// <summary>The typedValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.CustomAttributeTypedArgument? TypedValue { get; set; }
#nullable restore
#else
        public ApiSdk.Models.CustomAttributeTypedArgument TypedValue { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.CustomAttributeNamedArgument"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.CustomAttributeNamedArgument CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.CustomAttributeNamedArgument();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isField", n => { IsField = n.GetBoolValue(); } },
                { "memberInfo", n => { MemberInfo = n.GetObjectValue<ApiSdk.Models.MemberInfo>(ApiSdk.Models.MemberInfo.CreateFromDiscriminatorValue); } },
                { "memberName", n => { MemberName = n.GetStringValue(); } },
                { "typedValue", n => { TypedValue = n.GetObjectValue<ApiSdk.Models.CustomAttributeTypedArgument>(ApiSdk.Models.CustomAttributeTypedArgument.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ApiSdk.Models.MemberInfo>("memberInfo", MemberInfo);
            writer.WriteObjectValue<ApiSdk.Models.CustomAttributeTypedArgument>("typedValue", TypedValue);
        }
    }
}
