// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class FieldInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The attributes property</summary>
        public int? Attributes { get; set; }
        /// <summary>The customAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeData>? CustomAttributes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeData> CustomAttributes { get; private set; }
#endif
        /// <summary>The declaringType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? DeclaringType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject DeclaringType { get; set; }
#endif
        /// <summary>The fieldHandle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.RuntimeFieldHandleObject? FieldHandle { get; set; }
#nullable restore
#else
        public ApiSdk.Models.RuntimeFieldHandleObject FieldHandle { get; set; }
#endif
        /// <summary>The fieldType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? FieldType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject FieldType { get; set; }
#endif
        /// <summary>The isAssembly property</summary>
        public bool? IsAssembly { get; private set; }
        /// <summary>The isCollectible property</summary>
        public bool? IsCollectible { get; private set; }
        /// <summary>The isFamily property</summary>
        public bool? IsFamily { get; private set; }
        /// <summary>The isFamilyAndAssembly property</summary>
        public bool? IsFamilyAndAssembly { get; private set; }
        /// <summary>The isFamilyOrAssembly property</summary>
        public bool? IsFamilyOrAssembly { get; private set; }
        /// <summary>The isInitOnly property</summary>
        public bool? IsInitOnly { get; private set; }
        /// <summary>The isLiteral property</summary>
        public bool? IsLiteral { get; private set; }
        /// <summary>The isNotSerialized property</summary>
        [Obsolete("")]
        public bool? IsNotSerialized { get; private set; }
        /// <summary>The isPinvokeImpl property</summary>
        public bool? IsPinvokeImpl { get; private set; }
        /// <summary>The isPrivate property</summary>
        public bool? IsPrivate { get; private set; }
        /// <summary>The isPublic property</summary>
        public bool? IsPublic { get; private set; }
        /// <summary>The isSecurityCritical property</summary>
        public bool? IsSecurityCritical { get; private set; }
        /// <summary>The isSecuritySafeCritical property</summary>
        public bool? IsSecuritySafeCritical { get; private set; }
        /// <summary>The isSecurityTransparent property</summary>
        public bool? IsSecurityTransparent { get; private set; }
        /// <summary>The isSpecialName property</summary>
        public bool? IsSpecialName { get; private set; }
        /// <summary>The isStatic property</summary>
        public bool? IsStatic { get; private set; }
        /// <summary>The memberType property</summary>
        public int? MemberType { get; set; }
        /// <summary>The metadataToken property</summary>
        public int? MetadataToken { get; private set; }
        /// <summary>The module property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.Module? Module { get; set; }
#nullable restore
#else
        public ApiSdk.Models.Module Module { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>The reflectedType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? ReflectedType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject ReflectedType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.FieldInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.FieldInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.FieldInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetIntValue(); } },
                { "customAttributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeData>(ApiSdk.Models.CustomAttributeData.CreateFromDiscriminatorValue)?.ToList(); } },
                { "declaringType", n => { DeclaringType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
                { "fieldHandle", n => { FieldHandle = n.GetObjectValue<ApiSdk.Models.RuntimeFieldHandleObject>(ApiSdk.Models.RuntimeFieldHandleObject.CreateFromDiscriminatorValue); } },
                { "fieldType", n => { FieldType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
                { "isAssembly", n => { IsAssembly = n.GetBoolValue(); } },
                { "isCollectible", n => { IsCollectible = n.GetBoolValue(); } },
                { "isFamily", n => { IsFamily = n.GetBoolValue(); } },
                { "isFamilyAndAssembly", n => { IsFamilyAndAssembly = n.GetBoolValue(); } },
                { "isFamilyOrAssembly", n => { IsFamilyOrAssembly = n.GetBoolValue(); } },
                { "isInitOnly", n => { IsInitOnly = n.GetBoolValue(); } },
                { "isLiteral", n => { IsLiteral = n.GetBoolValue(); } },
                { "isNotSerialized", n => { IsNotSerialized = n.GetBoolValue(); } },
                { "isPinvokeImpl", n => { IsPinvokeImpl = n.GetBoolValue(); } },
                { "isPrivate", n => { IsPrivate = n.GetBoolValue(); } },
                { "isPublic", n => { IsPublic = n.GetBoolValue(); } },
                { "isSecurityCritical", n => { IsSecurityCritical = n.GetBoolValue(); } },
                { "isSecuritySafeCritical", n => { IsSecuritySafeCritical = n.GetBoolValue(); } },
                { "isSecurityTransparent", n => { IsSecurityTransparent = n.GetBoolValue(); } },
                { "isSpecialName", n => { IsSpecialName = n.GetBoolValue(); } },
                { "isStatic", n => { IsStatic = n.GetBoolValue(); } },
                { "memberType", n => { MemberType = n.GetIntValue(); } },
                { "metadataToken", n => { MetadataToken = n.GetIntValue(); } },
                { "module", n => { Module = n.GetObjectValue<ApiSdk.Models.Module>(ApiSdk.Models.Module.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reflectedType", n => { ReflectedType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attributes", Attributes);
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("declaringType", DeclaringType);
            writer.WriteObjectValue<ApiSdk.Models.RuntimeFieldHandleObject>("fieldHandle", FieldHandle);
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("fieldType", FieldType);
            writer.WriteIntValue("memberType", MemberType);
            writer.WriteObjectValue<ApiSdk.Models.Module>("module", Module);
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("reflectedType", ReflectedType);
        }
    }
}
