// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class JobLoadException : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.JobLoadException_data? Data { get; private set; }
#nullable restore
#else
        public ApiSdk.Models.JobLoadException_data Data { get; private set; }
#endif
        /// <summary>The helpLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpLink { get; set; }
#nullable restore
#else
        public string HelpLink { get; set; }
#endif
        /// <summary>The hResult property</summary>
        public int? HResult { get; set; }
        /// <summary>The innerException property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.ExceptionObject? InnerException { get; set; }
#nullable restore
#else
        public ApiSdk.Models.ExceptionObject InnerException { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; private set; }
#nullable restore
#else
        public string Message { get; private set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The stackTrace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StackTrace { get; private set; }
#nullable restore
#else
        public string StackTrace { get; private set; }
#endif
        /// <summary>The targetSite property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.MethodBase? TargetSite { get; set; }
#nullable restore
#else
        public ApiSdk.Models.MethodBase TargetSite { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.JobLoadException"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.JobLoadException CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.JobLoadException();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<ApiSdk.Models.JobLoadException_data>(ApiSdk.Models.JobLoadException_data.CreateFromDiscriminatorValue); } },
                { "hResult", n => { HResult = n.GetIntValue(); } },
                { "helpLink", n => { HelpLink = n.GetStringValue(); } },
                { "innerException", n => { InnerException = n.GetObjectValue<ApiSdk.Models.ExceptionObject>(ApiSdk.Models.ExceptionObject.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "stackTrace", n => { StackTrace = n.GetStringValue(); } },
                { "targetSite", n => { TargetSite = n.GetObjectValue<ApiSdk.Models.MethodBase>(ApiSdk.Models.MethodBase.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("helpLink", HelpLink);
            writer.WriteIntValue("hResult", HResult);
            writer.WriteObjectValue<ApiSdk.Models.ExceptionObject>("innerException", InnerException);
            writer.WriteStringValue("source", Source);
            writer.WriteObjectValue<ApiSdk.Models.MethodBase>("targetSite", TargetSite);
        }
    }
}
