// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class MemberInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeData>? CustomAttributes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeData> CustomAttributes { get; private set; }
#endif
        /// <summary>The declaringType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? DeclaringType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject DeclaringType { get; set; }
#endif
        /// <summary>The isCollectible property</summary>
        public bool? IsCollectible { get; private set; }
        /// <summary>The memberType property</summary>
        public int? MemberType { get; set; }
        /// <summary>The metadataToken property</summary>
        public int? MetadataToken { get; private set; }
        /// <summary>The module property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.Module? Module { get; set; }
#nullable restore
#else
        public ApiSdk.Models.Module Module { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>The reflectedType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? ReflectedType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject ReflectedType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.MemberInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.MemberInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.MemberInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customAttributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeData>(ApiSdk.Models.CustomAttributeData.CreateFromDiscriminatorValue)?.ToList(); } },
                { "declaringType", n => { DeclaringType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
                { "isCollectible", n => { IsCollectible = n.GetBoolValue(); } },
                { "memberType", n => { MemberType = n.GetIntValue(); } },
                { "metadataToken", n => { MetadataToken = n.GetIntValue(); } },
                { "module", n => { Module = n.GetObjectValue<ApiSdk.Models.Module>(ApiSdk.Models.Module.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reflectedType", n => { ReflectedType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("declaringType", DeclaringType);
            writer.WriteIntValue("memberType", MemberType);
            writer.WriteObjectValue<ApiSdk.Models.Module>("module", Module);
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("reflectedType", ReflectedType);
        }
    }
}
