// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class Module : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assembly property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.Assembly? Assembly { get; set; }
#nullable restore
#else
        public ApiSdk.Models.Assembly Assembly { get; set; }
#endif
        /// <summary>The customAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeData>? CustomAttributes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeData> CustomAttributes { get; private set; }
#endif
        /// <summary>The fullyQualifiedName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullyQualifiedName { get; private set; }
#nullable restore
#else
        public string FullyQualifiedName { get; private set; }
#endif
        /// <summary>The mdStreamVersion property</summary>
        public int? MdStreamVersion { get; private set; }
        /// <summary>The metadataToken property</summary>
        public int? MetadataToken { get; private set; }
        /// <summary>The moduleHandle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.ModuleHandleObject? ModuleHandle { get; set; }
#nullable restore
#else
        public ApiSdk.Models.ModuleHandleObject ModuleHandle { get; set; }
#endif
        /// <summary>The moduleVersionId property</summary>
        public Guid? ModuleVersionId { get; private set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>The scopeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScopeName { get; private set; }
#nullable restore
#else
        public string ScopeName { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.Module"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.Module CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.Module();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assembly", n => { Assembly = n.GetObjectValue<ApiSdk.Models.Assembly>(ApiSdk.Models.Assembly.CreateFromDiscriminatorValue); } },
                { "customAttributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeData>(ApiSdk.Models.CustomAttributeData.CreateFromDiscriminatorValue)?.ToList(); } },
                { "fullyQualifiedName", n => { FullyQualifiedName = n.GetStringValue(); } },
                { "mdStreamVersion", n => { MdStreamVersion = n.GetIntValue(); } },
                { "metadataToken", n => { MetadataToken = n.GetIntValue(); } },
                { "moduleHandle", n => { ModuleHandle = n.GetObjectValue<ApiSdk.Models.ModuleHandleObject>(ApiSdk.Models.ModuleHandleObject.CreateFromDiscriminatorValue); } },
                { "moduleVersionId", n => { ModuleVersionId = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scopeName", n => { ScopeName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ApiSdk.Models.Assembly>("assembly", Assembly);
            writer.WriteObjectValue<ApiSdk.Models.ModuleHandleObject>("moduleHandle", ModuleHandle);
        }
    }
}
