// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class ParameterInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The attributes property</summary>
        public int? Attributes { get; set; }
        /// <summary>The customAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ApiSdk.Models.CustomAttributeData>? CustomAttributes { get; private set; }
#nullable restore
#else
        public List<ApiSdk.Models.CustomAttributeData> CustomAttributes { get; private set; }
#endif
        /// <summary>The defaultValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DefaultValue { get; private set; }
#nullable restore
#else
        public UntypedNode DefaultValue { get; private set; }
#endif
        /// <summary>The hasDefaultValue property</summary>
        public bool? HasDefaultValue { get; private set; }
        /// <summary>The isIn property</summary>
        public bool? IsIn { get; private set; }
        /// <summary>The isLcid property</summary>
        public bool? IsLcid { get; private set; }
        /// <summary>The isOptional property</summary>
        public bool? IsOptional { get; private set; }
        /// <summary>The isOut property</summary>
        public bool? IsOut { get; private set; }
        /// <summary>The isRetval property</summary>
        public bool? IsRetval { get; private set; }
        /// <summary>The member property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.MemberInfo? Member { get; set; }
#nullable restore
#else
        public ApiSdk.Models.MemberInfo Member { get; set; }
#endif
        /// <summary>The metadataToken property</summary>
        public int? MetadataToken { get; private set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>The parameterType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.TypeObject? ParameterType { get; set; }
#nullable restore
#else
        public ApiSdk.Models.TypeObject ParameterType { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; private set; }
        /// <summary>The rawDefaultValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RawDefaultValue { get; private set; }
#nullable restore
#else
        public UntypedNode RawDefaultValue { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.ParameterInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.ParameterInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.ParameterInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetIntValue(); } },
                { "customAttributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<ApiSdk.Models.CustomAttributeData>(ApiSdk.Models.CustomAttributeData.CreateFromDiscriminatorValue)?.ToList(); } },
                { "defaultValue", n => { DefaultValue = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "hasDefaultValue", n => { HasDefaultValue = n.GetBoolValue(); } },
                { "isIn", n => { IsIn = n.GetBoolValue(); } },
                { "isLcid", n => { IsLcid = n.GetBoolValue(); } },
                { "isOptional", n => { IsOptional = n.GetBoolValue(); } },
                { "isOut", n => { IsOut = n.GetBoolValue(); } },
                { "isRetval", n => { IsRetval = n.GetBoolValue(); } },
                { "member", n => { Member = n.GetObjectValue<ApiSdk.Models.MemberInfo>(ApiSdk.Models.MemberInfo.CreateFromDiscriminatorValue); } },
                { "metadataToken", n => { MetadataToken = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameterType", n => { ParameterType = n.GetObjectValue<ApiSdk.Models.TypeObject>(ApiSdk.Models.TypeObject.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "rawDefaultValue", n => { RawDefaultValue = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attributes", Attributes);
            writer.WriteObjectValue<ApiSdk.Models.MemberInfo>("member", Member);
            writer.WriteObjectValue<ApiSdk.Models.TypeObject>("parameterType", ParameterType);
        }
    }
}
