// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models
{
    #pragma warning disable CS1591
    public class ImagesListResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The containers property</summary>
        public long? Containers { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ApiSdk.Models.ImagesListResponse_labels? Labels { get; set; }
#nullable restore
#else
        public ApiSdk.Models.ImagesListResponse_labels Labels { get; set; }
#endif
        /// <summary>The parentID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentID { get; set; }
#nullable restore
#else
        public string ParentID { get; set; }
#endif
        /// <summary>The repoDigests property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RepoDigests { get; set; }
#nullable restore
#else
        public List<string> RepoDigests { get; set; }
#endif
        /// <summary>The repoTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RepoTags { get; set; }
#nullable restore
#else
        public List<string> RepoTags { get; set; }
#endif
        /// <summary>The sharedSize property</summary>
        public long? SharedSize { get; set; }
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The virtualSize property</summary>
        public long? VirtualSize { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Models.ImagesListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ApiSdk.Models.ImagesListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ApiSdk.Models.ImagesListResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "containers", n => { Containers = n.GetLongValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<ApiSdk.Models.ImagesListResponse_labels>(ApiSdk.Models.ImagesListResponse_labels.CreateFromDiscriminatorValue); } },
                { "parentID", n => { ParentID = n.GetStringValue(); } },
                { "repoDigests", n => { RepoDigests = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                { "repoTags", n => { RepoTags = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                { "sharedSize", n => { SharedSize = n.GetLongValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "virtualSize", n => { VirtualSize = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("containers", Containers);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<ApiSdk.Models.ImagesListResponse_labels>("labels", Labels);
            writer.WriteStringValue("parentID", ParentID);
            writer.WriteCollectionOfPrimitiveValues<string>("repoDigests", RepoDigests);
            writer.WriteCollectionOfPrimitiveValues<string>("repoTags", RepoTags);
            writer.WriteLongValue("sharedSize", SharedSize);
            writer.WriteLongValue("size", Size);
            writer.WriteLongValue("virtualSize", VirtualSize);
        }
    }
}
